taxi/app/urls.py
from django.urls import path
from .views import CarView, ViewCar

urlpatterns = [
    # path('', PriceView.as_view(), name='home'),
    path('', CarView.as_view(), name='home'),
    path('car/<int:pk>/', ViewCar.as_view(), name='views_car'),
]

taxi/taxi/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("app.urls")),
]

taxi/app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Firm(models.Model):
    firm_name = models.TextField(blank=False, verbose_name="Название фирмы")
    def __str__(self):
        return self.firm_name

class Rate(models.Model):
    rate_name = models.TextField(blank=False, verbose_name="Название тарифа")
    
    def __str__(self):
        return self.rate_name

class Car(models.Model):
    car_name = models.TextField(blank=False, verbose_name="Название тарифа")
    
    def __str__(self):
        return self.car_name

    def get_absolute_url(self):
        return reverse('views_car', kwargs={"pk": self.pk})

class Price(models.Model):
    firm = models.ForeignKey(
        "Firm", on_delete=models.PROTECT, verbose_name="Фирма"
    )
    rate = models.ForeignKey(
        "Rate", on_delete=models.PROTECT, verbose_name="Фирма"
    )
    car = models.ForeignKey(
        "Car", on_delete=models.PROTECT, verbose_name="Фирма"
    )
    price = models.IntegerField(blank=False, verbose_name="Цена")

taxi/app/views.py
from django.shortcuts import render
from .models import Price, Car, Firm, Rate
from django.views.generic import ListView, DetailView
# Create your views here.

# class PriceView(ListView):
#     model = Price
#     template_name: str = "app/home.html"
#     context_object_name = 'price'
#     allow_empty: bool = True

    # def get_context_data(self, **kwargs):
    #     context = super(PriceView, self).get_context_data(**kwargs)
    #     context['car'] = Car.objects.all()
    #     context['firm'] = Firm.objects.all()
    #     context['rate'] = Rate.objects.all()
    #     # And so on for more models
    #     return context

class CarView(ListView):
    model = Car
    template_name: str = "app/home.html"
    context_object_name = 'car'
    allow_empty: bool = True

class ViewCar(DetailView):
    model = Car
    template_name: str = "app/views_car.html"
    context_object_name = 'car_item'

taxi/app/templates/app/home.html
{% for item in car %}
<div class="card mb-3">
  <div class="card-body">
    <div class="media">
      <div class="media-body">
        <h5 class="card-title {% cycle 'text-danger' 'text-success' %}">{{ item.car_name }}</h5>
        <a href="{{ item.get_absolute_url }}" class="btn btn-primary">Показать</a>
      </div>
    </div>
  </div>
</div>
{% empty %}
Oops...
{% endfor %}

taxi/app/templates/app/views_car.html
<html lang="en">
<html xmlns:th="https://www.thymeleaf.org">
<h1>{{ car_item.car_name }}</h1>
<table border="1">
    <tr>
        <th>Фирма</th>
        <th>Тариф</th>
        <th>Цена(руб/км)</th>

    </tr>
    {% for item in car_item.price_set.all|dictsort:"firm.firm_name" %}
    <tr th:each = "">
        <td th:text="">{{ item.firm.firm_name }}</td>
        <td th:text="">{{ item.rate.rate_name}}</td>
        <td th:text="">{{ item.price}}</td>
    </tr>
    {% endfor %}
</table>
<body>
<br>
<br>
<br>
</body>
</html>